@Test public void testClose() throws Exception {
Assert.fail("IOException should have been thrown");
Assert.fail("IOException should have been thrown");
}